### ISSUE TITLE
Could not find module `apollo-link-context`

### ISSUE THREAD

**Issue by marsh73** [ember-graphql/ember-apollo-client#274] opened 2019-04-02 13:33 UTC
This issue seems to be similar to #137 but that was closed, seemingly without any fix or update. I was having lots of trouble getting ember-apollo-client to work in my actual application. Our Ember version is a bit out of date, so I created a new project just to get this running, so i can rule out version conflicts.

I'm trying to add some headers to my requests, but it doesn't seem to know how to load `apollo-link-context`. I see it in my node_modules, but am not sure what the problem is. 

```
import { computed } from "@ember/object";
import ApolloService from "ember-apollo-client/services/apollo";
import { setContext } from "apollo-link-context";

export default ApolloService.extend({

  link: computed(function() {
    let httpLink = this._super(...arguments);

    let authLink = setContext((request, context) => {
      return this._runAuthorize(request, context);
    });
    return authLink.concat(httpLink);
  }),

  _runAuthorize() {
    let headers = {};
    headers['x-user-id'] = '100';
    headers['x-user-uuid'] = 'jahhalhahoyhhalh';
    return headers;
  }
});

```
the error i'm seeing looks like:

![Screen Shot 2019-04-02 at 6 34 33 AM](https://user-images.githubusercontent.com/645730/55406680-6e02e800-5511-11e9-8143-a6e377e68f33.png)

**Comment by marsh73** [comment] 2019-04-02 14:53
after manually installing ember-auto-import into my application, i'm no longer seeing that error... but now i'm seeing... 
![Screen Shot 2019-04-02 at 7 52 53 AM](https://user-images.githubusercontent.com/645730/55412472-58df8680-551c-11e9-85a4-be0cc347b17d.png)

**Comment by marsh73** [comment] 2019-04-02 15:19
as you can see in my code... i am attempting to extend the ApolloService. I then inject that service into my route, which seems to be what is causing the problem. if i do not inject it, I don't see those issues, but i also don't inject those headers. So i am missing a step along the way somewhere. when extending the ApolloService... how should i be using that?

**Comment by sumeetattree** [comment] 2019-04-03 13:36
My use case is within an engine.

I am facing the same issue. I am trying to extend `ApolloService` inside an engine and running into the same import error.

Moving the `ember-auto-import` dependency to the `engine`'s `package.json` did not help.

**Comment by josemarluedke** [comment] 2019-04-03 13:43
Hello @marsh73 and @sumeetattree!

If you are loading `apollo-link-context` from your app, you must add it as a direct dependency. 

For example:

You are overwriting the apollo service in your app (or engine). If in that file you are importing `apollo-link-context` or any other dependency, you need to add them to your `devDependencies` as well `ember-auto-import`. If you are in an engine, I believe you need to add it to `dependencies`.

Let me know if that solved your problem.

**Comment by sumeetattree** [comment] 2019-04-03 14:14
Hi @josemarluedke that did the trick. Thank you! :)

Needed to add and import both `apollo-link-context` and `ember-auto-import` manually.

Maybe add this caveat to the documentation? It is not really evident that `ember-auto-import` also needs to be present inside the `dependencies` especially when one is trying to consume the addon from inside another addon or engine.

**Comment by crowjonah** [comment] 2019-04-03 21:37
This back and forth was super helpful in handling a simple Github GraphQL header auth token. Beyond making sure `apollo-link-context` and `ember-auto-import` are both installed/imported, another point of clarification for the docs, since it tripped me up: redefining `link` as a computed property worked when done directly on the extended `ApolloService`, and not as a nested property of `clientOptions`.

**Comment by bgentry** [comment] 2019-04-03 22:14
ember-auto-import [is listed in our package.json](https://github.com/bgentry/ember-apollo-client/blob/988d86030181e093e47d4b6a4b349531e3713794/package.json#L36). Is this not actually working as intended? You're saying you have to separately install it?

**Comment by marsh73** [comment] 2019-04-03 23:49
that did the trick for me. Thanks @josemarluedke. Is this expected behavior when using `ember-auto-import`?  this almost makes sense, but certainly banged my head against the wall for a while trying to get that working.

**Comment by marsh73** [comment] 2019-04-04 00:47
i thought that worked, but realized that i hadn't been injecting the overridden apollo service. Now i'm wondering if this is a separate problem. `Uncaught TypeError: this.get(...).markSubscriptionsStale is not a function` 
the same as the screenshot ☝️ 

my route code looks like this ```import Route from "@ember/routing/route";
import { RouteQueryManager } from "ember-apollo-client";
import query from "../queries/dbaas";
import { inject as service } from '@ember/service';

export default Route.extend(RouteQueryManager, {
  apollo: service(),
  model() {
    return this.get('apollo').query({ query });
  },

  setupController: function(controller, model) {
    controller.set('databases', model.DBaaSList.clusters);
  }
});
```
wondering if maybe i'm using that `RouteQueryManager` improperly 🤔

**Comment by josemarluedke** [comment] 2019-04-04 03:59
I don’t think you need to inject the apollo service when using the mixin.

**Comment by sumeetattree** [comment] 2019-04-04 04:17
@bgentry I was surprised too.

Even then, I expected that app-wide install of `ember-auto-import` would have sufficed. But apparently you have to add it your `addon/engine`'s `dependencies` that's consuming `ember-apollo-client`. Again I am not sure if this is the default behavior of `ember-auto-import`. 

I have not tried it in a plain ember app so won't be able to comment on that.

@josemarluedke That's weird though. Even if you were overriding the `apollo` service, I would have thought that you will be able to use it with the `RouteQueryManager`. As I see it you might have customized the service but still want to be able to use the niceties that come with `RouteQueryManager`. What am I missing?

**Comment by marsh73** [comment] 2019-04-04 13:03
> I don’t think you need to inject the apollo service when using the mixin.

@sumeetattree is describing what I have been trying to do. I am extending ApolloService to add some custom headers to my graphql requests. If I don't inject the service, Ember grabs the addon service. 

And I was using `RouteQueryManager` to no avail.

**Comment by marsh73** [comment] 2019-04-04 22:22
this worked for me. moving on to the next hurdle. Thank you all.

**Comment by marsh73** [comment] 2019-04-04 23:11
started forking the howtographql repo to update to the v2 of the addon. https://github.com/marsh73/ember-apollo until i got to the graphcool updates as well. If i find some time I'll get back to it. Unless someone gets to it first.

**Comment by jcfinnerup** [comment] 2019-05-07 13:39
> I don’t think you need to inject the apollo service when using the mixin.

Could you clarify? 
Im injecting the service too and if there's another way to do it that would be swell

**Comment by josemarluedke** [comment] 2019-07-31 22:35
@jcfinnerup well, you do not need to inject the service when you are using the mixing (for example RouteQueryManager) because it does that for you.

Here is an example from the readme:
```js
import Route from "@ember/routing/route";
import { RouteQueryManager } from "ember-apollo-client";
import query from "my-app/gql/queries/human";

export default Route.extend(RouteQueryManager, {
  model(params) {
    let variables = { id: params.id };
    return this.get('apollo').watchQuery({ query, variables }, "human");
  }
});
```

As you can see, there is no inject in this case and we are using `this.get('apollo')`, which is the point of this mixin. 


Now, if you are not using any of these mixins, then yes, you should be injecting the service.

Hopefully, this is clear now. 

Closing this as the main issue has been solved. Thanks all.

**Closed by josemarluedke** 2019-07-31 22:35 UTC
